<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Trash</name>
   <tag></tag>
   <elementGuidId>03e1dbaa-74cc-4490-94e1-ef48dca6ea9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='occ-wishlist']/div/div/div/div[2]/div[3]/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-trash-alt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occ-wishlist&quot;)/div[@class=&quot;offcanvas-cart-body offcanvas-scrollable&quot;]/div[@class=&quot;offcanvas-cart-items&quot;]/div[@class=&quot;offcanvas-cart-item&quot;]/div[@class=&quot;row sm-gutters flex-wrap align-items-center mt-2&quot;]/div[@class=&quot;ml-auto text-nowrap&quot;]/a[@class=&quot;btn btn-secondary btn-to-danger btn-sm btn-icon remove ajax-cart-link&quot;]/i[@class=&quot;far fa-trash-alt&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='occ-wishlist']/div/div/div/div[2]/div[3]/a[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
